version: '3.8'
services:
  web:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
